channels:
  - conda-forge
dependencies:
  - python=3.6
  - jupyterlab=0.34.0
  - nodejs=8.9
  - notebook=5.6.0
  - nbconvert
  - ipykernel=4.7
  - pip
  - numpy=1.15.0
  - pandas=0.23.4
  - matplotlib
  - plotly
  - invoke
