name: biocomp_bootcamp
channels:
  - conda-forge
  #- intel
dependencies:
  - python=3.7
  - pip
 #   - jupyter_contrib_nbextensions
 # - jupyter
 # - notebook
 # - jupyterlab
 # - numpy
 # - pandas
 # - matplotlib
 # - plotly
 # - ipywidgets
